import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import "flexboxgrid2";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="header">
          <div className="container">
            <div className="row">
              <div className="col-xs-12">
                <div style={{ display: "flex", userSelect: "none" }}>
                  <h1 style={{ margin: "0 15px", color: "#0958d9" }}>
                    SoccerStat
                  </h1>
                  <ul className="nav">
                    <li>
                      <Link href="/">Лиги</Link>
                    </li>

                    <li>
                      <Link href="/teams">Команды</Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
